; King's Quest I Hebrew Patch Installer
; NSIS Script

;--------------------------------
; General Attributes

Name "King's Quest I - תרגום עברי"
OutFile "KQ1_Hebrew_Patch_Setup.exe"
InstallDir ""
RequestExecutionLevel admin

;--------------------------------
; Version Information

VIProductVersion "1.0.0.0"
VIAddVersionKey "ProductName" "King's Quest I Hebrew Patch"
VIAddVersionKey "FileDescription" "Hebrew Translation Patch for King's Quest I"
VIAddVersionKey "FileVersion" "1.0.0.0"
VIAddVersionKey "ProductVersion" "1.0.0.0"
VIAddVersionKey "LegalCopyright" "Hebrew Translation Team"

;--------------------------------
; Modern UI

!include "MUI2.nsh"

;--------------------------------
; MUI Settings

!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Custom Hebrew text
!define MUI_WELCOMEPAGE_TITLE "ברוכים הבאים להתקנת התרגום העברי"
!define MUI_WELCOMEPAGE_TEXT "אשף זה ידריך אותך בהתקנת התרגום העברי למשחק King's Quest I.$\r$\n$\r$\nלחץ 'הבא' כדי להמשיך."
!define MUI_DIRECTORYPAGE_TEXT_TOP "בחר את תיקיית המשחק שבה מותקן King's Quest I."
!define MUI_FINISHPAGE_TITLE "ההתקנה הושלמה בהצלחה"
!define MUI_FINISHPAGE_TEXT "התרגום העברי הותקן בהצלחה.$\r$\n$\r$\nלחץ 'סיום' כדי לסגור אשף זה."

;--------------------------------
; Pages

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

;--------------------------------
; Languages

!insertmacro MUI_LANGUAGE "Hebrew"

;--------------------------------
; Validation Function

Function .onVerifyInstDir
  ; Check if resource.map exists
  IfFileExists "$INSTDIR\resource.map" 0 invalid_dir
  
  ; Get file size of resource.map
  ClearErrors
  FileOpen $0 "$INSTDIR\resource.map" r
  FileSeek $0 0 END $1
  FileClose $0
  
  ; Check if file size is exactly 5,790 bytes (KQ1 SCI0 resource.map)
  IntCmp $1 5790 valid_dir invalid_dir invalid_dir
  
  valid_dir:
    ; Directory is valid
    Return
  
  invalid_dir:
    ; Directory is invalid - abort
    Abort
FunctionEnd

;--------------------------------
; Installer Sections

Section "King's Quest I Hebrew Patch" SecMain

  SetOutPath "$INSTDIR"
  
  ; Set overwrite on to replace existing files
  SetOverwrite try
  
  ; Copy assets (fonts, title pic, view, vocab)
  File "games_assets\kq1\bin\font.000"
  File "games_assets\kq1\bin\font.004"
  File "games_assets\kq1\bin\font.300"
  File "games_assets\kq1\bin\font.999"
  File "games_assets\kq1\bin\pic.902"
  File "games_assets\kq1\bin\view.511"
  File "games_assets\kq1\bin\view.913"
  File "games_assets\kq1\bin\vocab.900"
  
  ; Copy all script files
  File "games_assets\kq1\bin\script.000"
  File "games_assets\kq1\bin\script.001"
  File "games_assets\kq1\bin\script.002"
  File "games_assets\kq1\bin\script.003"
  File "games_assets\kq1\bin\script.004"
  File "games_assets\kq1\bin\script.005"
  File "games_assets\kq1\bin\script.006"
  File "games_assets\kq1\bin\script.007"
  File "games_assets\kq1\bin\script.008"
  File "games_assets\kq1\bin\script.009"
  File "games_assets\kq1\bin\script.010"
  File "games_assets\kq1\bin\script.012"
  File "games_assets\kq1\bin\script.013"
  File "games_assets\kq1\bin\script.014"
  File "games_assets\kq1\bin\script.015"
  File "games_assets\kq1\bin\script.016"
  File "games_assets\kq1\bin\script.017"
  File "games_assets\kq1\bin\script.019"
  File "games_assets\kq1\bin\script.020"
  File "games_assets\kq1\bin\script.021"
  File "games_assets\kq1\bin\script.022"
  File "games_assets\kq1\bin\script.023"
  File "games_assets\kq1\bin\script.024"
  File "games_assets\kq1\bin\script.025"
  File "games_assets\kq1\bin\script.026"
  File "games_assets\kq1\bin\script.027"
  File "games_assets\kq1\bin\script.028"
  File "games_assets\kq1\bin\script.029"
  File "games_assets\kq1\bin\script.030"
  File "games_assets\kq1\bin\script.031"
  File "games_assets\kq1\bin\script.032"
  File "games_assets\kq1\bin\script.033"
  File "games_assets\kq1\bin\script.034"
  File "games_assets\kq1\bin\script.035"
  File "games_assets\kq1\bin\script.036"
  File "games_assets\kq1\bin\script.037"
  File "games_assets\kq1\bin\script.038"
  File "games_assets\kq1\bin\script.039"
  File "games_assets\kq1\bin\script.040"
  File "games_assets\kq1\bin\script.041"
  File "games_assets\kq1\bin\script.042"
  File "games_assets\kq1\bin\script.043"
  File "games_assets\kq1\bin\script.044"
  File "games_assets\kq1\bin\script.045"
  File "games_assets\kq1\bin\script.046"
  File "games_assets\kq1\bin\script.047"
  File "games_assets\kq1\bin\script.048"
  File "games_assets\kq1\bin\script.049"
  File "games_assets\kq1\bin\script.051"
  File "games_assets\kq1\bin\script.052"
  File "games_assets\kq1\bin\script.053"
  File "games_assets\kq1\bin\script.056"
  File "games_assets\kq1\bin\script.057"
  File "games_assets\kq1\bin\script.058"
  File "games_assets\kq1\bin\script.060"
  File "games_assets\kq1\bin\script.061"
  File "games_assets\kq1\bin\script.062"
  File "games_assets\kq1\bin\script.063"
  File "games_assets\kq1\bin\script.065"
  File "games_assets\kq1\bin\script.066"
  File "games_assets\kq1\bin\script.067"
  File "games_assets\kq1\bin\script.068"
  File "games_assets\kq1\bin\script.069"
  File "games_assets\kq1\bin\script.070"
  File "games_assets\kq1\bin\script.071"
  File "games_assets\kq1\bin\script.072"
  File "games_assets\kq1\bin\script.073"
  File "games_assets\kq1\bin\script.074"
  File "games_assets\kq1\bin\script.075"
  File "games_assets\kq1\bin\script.076"
  File "games_assets\kq1\bin\script.077"
  File "games_assets\kq1\bin\script.078"
  File "games_assets\kq1\bin\script.079"
  File "games_assets\kq1\bin\script.080"
  File "games_assets\kq1\bin\script.083"
  File "games_assets\kq1\bin\script.084"
  File "games_assets\kq1\bin\script.085"
  File "games_assets\kq1\bin\script.095"
  File "games_assets\kq1\bin\script.200"
  File "games_assets\kq1\bin\script.255"
  File "games_assets\kq1\bin\script.603"
  File "games_assets\kq1\bin\script.605"
  File "games_assets\kq1\bin\script.606"
  File "games_assets\kq1\bin\script.607"
  File "games_assets\kq1\bin\script.608"
  File "games_assets\kq1\bin\script.609"
  File "games_assets\kq1\bin\script.610"
  File "games_assets\kq1\bin\script.612"
  File "games_assets\kq1\bin\script.613"
  File "games_assets\kq1\bin\script.779"
  File "games_assets\kq1\bin\script.800"
  File "games_assets\kq1\bin\script.803"
  File "games_assets\kq1\bin\script.987"
  File "games_assets\kq1\bin\script.990"
  File "games_assets\kq1\bin\script.994"
  File "games_assets\kq1\bin\script.995"
  File "games_assets\kq1\bin\script.996"
  File "games_assets\kq1\bin\script.997"
  
  ; Copy all text files
  File "games_assets\kq1\bin\text.000"
  File "games_assets\kq1\bin\text.001"
  File "games_assets\kq1\bin\text.002"
  File "games_assets\kq1\bin\text.003"
  File "games_assets\kq1\bin\text.004"
  File "games_assets\kq1\bin\text.005"
  File "games_assets\kq1\bin\text.006"
  File "games_assets\kq1\bin\text.007"
  File "games_assets\kq1\bin\text.008"
  File "games_assets\kq1\bin\text.009"
  File "games_assets\kq1\bin\text.010"
  File "games_assets\kq1\bin\text.011"
  File "games_assets\kq1\bin\text.012"
  File "games_assets\kq1\bin\text.013"
  File "games_assets\kq1\bin\text.014"
  File "games_assets\kq1\bin\text.015"
  File "games_assets\kq1\bin\text.016"
  File "games_assets\kq1\bin\text.017"
  File "games_assets\kq1\bin\text.018"
  File "games_assets\kq1\bin\text.019"
  File "games_assets\kq1\bin\text.020"
  File "games_assets\kq1\bin\text.021"
  File "games_assets\kq1\bin\text.022"
  File "games_assets\kq1\bin\text.023"
  File "games_assets\kq1\bin\text.024"
  File "games_assets\kq1\bin\text.025"
  File "games_assets\kq1\bin\text.026"
  File "games_assets\kq1\bin\text.027"
  File "games_assets\kq1\bin\text.028"
  File "games_assets\kq1\bin\text.029"
  File "games_assets\kq1\bin\text.030"
  File "games_assets\kq1\bin\text.031"
  File "games_assets\kq1\bin\text.032"
  File "games_assets\kq1\bin\text.033"
  File "games_assets\kq1\bin\text.034"
  File "games_assets\kq1\bin\text.035"
  File "games_assets\kq1\bin\text.036"
  File "games_assets\kq1\bin\text.037"
  File "games_assets\kq1\bin\text.038"
  File "games_assets\kq1\bin\text.039"
  File "games_assets\kq1\bin\text.040"
  File "games_assets\kq1\bin\text.041"
  File "games_assets\kq1\bin\text.042"
  File "games_assets\kq1\bin\text.043"
  File "games_assets\kq1\bin\text.044"
  File "games_assets\kq1\bin\text.045"
  File "games_assets\kq1\bin\text.046"
  File "games_assets\kq1\bin\text.047"
  File "games_assets\kq1\bin\text.048"
  File "games_assets\kq1\bin\text.049"
  File "games_assets\kq1\bin\text.050"
  File "games_assets\kq1\bin\text.051"
  File "games_assets\kq1\bin\text.052"
  File "games_assets\kq1\bin\text.053"
  File "games_assets\kq1\bin\text.058"
  File "games_assets\kq1\bin\text.059"
  File "games_assets\kq1\bin\text.062"
  File "games_assets\kq1\bin\text.063"
  File "games_assets\kq1\bin\text.065"
  File "games_assets\kq1\bin\text.066"
  File "games_assets\kq1\bin\text.067"
  File "games_assets\kq1\bin\text.068"
  File "games_assets\kq1\bin\text.069"
  File "games_assets\kq1\bin\text.070"
  File "games_assets\kq1\bin\text.071"
  File "games_assets\kq1\bin\text.072"
  File "games_assets\kq1\bin\text.073"
  File "games_assets\kq1\bin\text.074"
  File "games_assets\kq1\bin\text.075"
  File "games_assets\kq1\bin\text.076"
  File "games_assets\kq1\bin\text.077"
  File "games_assets\kq1\bin\text.078"
  File "games_assets\kq1\bin\text.079"
  File "games_assets\kq1\bin\text.080"
  File "games_assets\kq1\bin\text.083"
  File "games_assets\kq1\bin\text.085"
  File "games_assets\kq1\bin\text.087"
  File "games_assets\kq1\bin\text.090"
  File "games_assets\kq1\bin\text.200"
  File "games_assets\kq1\bin\text.255"
  File "games_assets\kq1\bin\text.600"
  File "games_assets\kq1\bin\text.601"
  File "games_assets\kq1\bin\text.603"
  File "games_assets\kq1\bin\text.604"
  File "games_assets\kq1\bin\text.605"
  File "games_assets\kq1\bin\text.606"
  File "games_assets\kq1\bin\text.607"
  File "games_assets\kq1\bin\text.608"
  File "games_assets\kq1\bin\text.609"
  File "games_assets\kq1\bin\text.610"
  File "games_assets\kq1\bin\text.611"
  File "games_assets\kq1\bin\text.612"
  File "games_assets\kq1\bin\text.613"
  File "games_assets\kq1\bin\text.616"
  File "games_assets\kq1\bin\text.780"
  File "games_assets\kq1\bin\text.782"
  File "games_assets\kq1\bin\text.784"
  File "games_assets\kq1\bin\text.800"
  File "games_assets\kq1\bin\text.803"
  File "games_assets\kq1\bin\text.804"
  File "games_assets\kq1\bin\text.899"
  File "games_assets\kq1\bin\text.950"
  File "games_assets\kq1\bin\text.990"
  File "games_assets\kq1\bin\text.993"
  File "games_assets\kq1\bin\text.994"
  File "games_assets\kq1\bin\text.996"
  File "games_assets\kq1\bin\text.997"
  File "games_assets\kq1\bin\text.999"
  
  ; Store installation folder
  WriteRegStr HKLM "Software\KQ1_Hebrew_Patch" "Install_Dir" "$INSTDIR"
  
  ; Create uninstaller
  WriteUninstaller "$INSTDIR\Uninstall_Hebrew_Patch.exe"
  
  ; Write uninstall registry keys
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KQ1_Hebrew_Patch" "DisplayName" "King's Quest I - Hebrew Patch"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KQ1_Hebrew_Patch" "UninstallString" '"$INSTDIR\Uninstall_Hebrew_Patch.exe"'
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KQ1_Hebrew_Patch" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KQ1_Hebrew_Patch" "NoRepair" 1

SectionEnd

;--------------------------------
; Uninstaller Section

Section "Uninstall"

  ; Remove asset files
  Delete "$INSTDIR\font.000"
  Delete "$INSTDIR\font.004"
  Delete "$INSTDIR\font.300"
  Delete "$INSTDIR\font.999"
  Delete "$INSTDIR\pic.902"
  Delete "$INSTDIR\view.511"
  Delete "$INSTDIR\view.913"
  Delete "$INSTDIR\vocab.900"
  
  ; Remove script files
  Delete "$INSTDIR\script.000"
  Delete "$INSTDIR\script.001"
  Delete "$INSTDIR\script.002"
  Delete "$INSTDIR\script.003"
  Delete "$INSTDIR\script.004"
  Delete "$INSTDIR\script.005"
  Delete "$INSTDIR\script.006"
  Delete "$INSTDIR\script.007"
  Delete "$INSTDIR\script.008"
  Delete "$INSTDIR\script.009"
  Delete "$INSTDIR\script.010"
  Delete "$INSTDIR\script.012"
  Delete "$INSTDIR\script.013"
  Delete "$INSTDIR\script.014"
  Delete "$INSTDIR\script.015"
  Delete "$INSTDIR\script.016"
  Delete "$INSTDIR\script.017"
  Delete "$INSTDIR\script.019"
  Delete "$INSTDIR\script.020"
  Delete "$INSTDIR\script.021"
  Delete "$INSTDIR\script.022"
  Delete "$INSTDIR\script.023"
  Delete "$INSTDIR\script.024"
  Delete "$INSTDIR\script.025"
  Delete "$INSTDIR\script.026"
  Delete "$INSTDIR\script.027"
  Delete "$INSTDIR\script.028"
  Delete "$INSTDIR\script.029"
  Delete "$INSTDIR\script.030"
  Delete "$INSTDIR\script.031"
  Delete "$INSTDIR\script.032"
  Delete "$INSTDIR\script.033"
  Delete "$INSTDIR\script.034"
  Delete "$INSTDIR\script.035"
  Delete "$INSTDIR\script.036"
  Delete "$INSTDIR\script.037"
  Delete "$INSTDIR\script.038"
  Delete "$INSTDIR\script.039"
  Delete "$INSTDIR\script.040"
  Delete "$INSTDIR\script.041"
  Delete "$INSTDIR\script.042"
  Delete "$INSTDIR\script.043"
  Delete "$INSTDIR\script.044"
  Delete "$INSTDIR\script.045"
  Delete "$INSTDIR\script.046"
  Delete "$INSTDIR\script.047"
  Delete "$INSTDIR\script.048"
  Delete "$INSTDIR\script.049"
  Delete "$INSTDIR\script.051"
  Delete "$INSTDIR\script.052"
  Delete "$INSTDIR\script.053"
  Delete "$INSTDIR\script.056"
  Delete "$INSTDIR\script.057"
  Delete "$INSTDIR\script.058"
  Delete "$INSTDIR\script.060"
  Delete "$INSTDIR\script.061"
  Delete "$INSTDIR\script.062"
  Delete "$INSTDIR\script.063"
  Delete "$INSTDIR\script.065"
  Delete "$INSTDIR\script.066"
  Delete "$INSTDIR\script.067"
  Delete "$INSTDIR\script.068"
  Delete "$INSTDIR\script.069"
  Delete "$INSTDIR\script.070"
  Delete "$INSTDIR\script.071"
  Delete "$INSTDIR\script.072"
  Delete "$INSTDIR\script.073"
  Delete "$INSTDIR\script.074"
  Delete "$INSTDIR\script.075"
  Delete "$INSTDIR\script.076"
  Delete "$INSTDIR\script.077"
  Delete "$INSTDIR\script.078"
  Delete "$INSTDIR\script.079"
  Delete "$INSTDIR\script.080"
  Delete "$INSTDIR\script.083"
  Delete "$INSTDIR\script.084"
  Delete "$INSTDIR\script.085"
  Delete "$INSTDIR\script.095"
  Delete "$INSTDIR\script.200"
  Delete "$INSTDIR\script.255"
  Delete "$INSTDIR\script.603"
  Delete "$INSTDIR\script.605"
  Delete "$INSTDIR\script.606"
  Delete "$INSTDIR\script.607"
  Delete "$INSTDIR\script.608"
  Delete "$INSTDIR\script.609"
  Delete "$INSTDIR\script.610"
  Delete "$INSTDIR\script.612"
  Delete "$INSTDIR\script.613"
  Delete "$INSTDIR\script.779"
  Delete "$INSTDIR\script.800"
  Delete "$INSTDIR\script.803"
  Delete "$INSTDIR\script.987"
  Delete "$INSTDIR\script.990"
  Delete "$INSTDIR\script.994"
  Delete "$INSTDIR\script.995"
  Delete "$INSTDIR\script.996"
  Delete "$INSTDIR\script.997"
  
  ; Remove text files
  Delete "$INSTDIR\text.000"
  Delete "$INSTDIR\text.001"
  Delete "$INSTDIR\text.002"
  Delete "$INSTDIR\text.003"
  Delete "$INSTDIR\text.004"
  Delete "$INSTDIR\text.005"
  Delete "$INSTDIR\text.006"
  Delete "$INSTDIR\text.007"
  Delete "$INSTDIR\text.008"
  Delete "$INSTDIR\text.009"
  Delete "$INSTDIR\text.010"
  Delete "$INSTDIR\text.011"
  Delete "$INSTDIR\text.012"
  Delete "$INSTDIR\text.013"
  Delete "$INSTDIR\text.014"
  Delete "$INSTDIR\text.015"
  Delete "$INSTDIR\text.016"
  Delete "$INSTDIR\text.017"
  Delete "$INSTDIR\text.018"
  Delete "$INSTDIR\text.019"
  Delete "$INSTDIR\text.020"
  Delete "$INSTDIR\text.021"
  Delete "$INSTDIR\text.022"
  Delete "$INSTDIR\text.023"
  Delete "$INSTDIR\text.024"
  Delete "$INSTDIR\text.025"
  Delete "$INSTDIR\text.026"
  Delete "$INSTDIR\text.027"
  Delete "$INSTDIR\text.028"
  Delete "$INSTDIR\text.029"
  Delete "$INSTDIR\text.030"
  Delete "$INSTDIR\text.031"
  Delete "$INSTDIR\text.032"
  Delete "$INSTDIR\text.033"
  Delete "$INSTDIR\text.034"
  Delete "$INSTDIR\text.035"
  Delete "$INSTDIR\text.036"
  Delete "$INSTDIR\text.037"
  Delete "$INSTDIR\text.038"
  Delete "$INSTDIR\text.039"
  Delete "$INSTDIR\text.040"
  Delete "$INSTDIR\text.041"
  Delete "$INSTDIR\text.042"
  Delete "$INSTDIR\text.043"
  Delete "$INSTDIR\text.044"
  Delete "$INSTDIR\text.045"
  Delete "$INSTDIR\text.046"
  Delete "$INSTDIR\text.047"
  Delete "$INSTDIR\text.048"
  Delete "$INSTDIR\text.049"
  Delete "$INSTDIR\text.050"
  Delete "$INSTDIR\text.051"
  Delete "$INSTDIR\text.052"
  Delete "$INSTDIR\text.053"
  Delete "$INSTDIR\text.058"
  Delete "$INSTDIR\text.059"
  Delete "$INSTDIR\text.062"
  Delete "$INSTDIR\text.063"
  Delete "$INSTDIR\text.065"
  Delete "$INSTDIR\text.066"
  Delete "$INSTDIR\text.067"
  Delete "$INSTDIR\text.068"
  Delete "$INSTDIR\text.069"
  Delete "$INSTDIR\text.070"
  Delete "$INSTDIR\text.071"
  Delete "$INSTDIR\text.072"
  Delete "$INSTDIR\text.073"
  Delete "$INSTDIR\text.074"
  Delete "$INSTDIR\text.075"
  Delete "$INSTDIR\text.076"
  Delete "$INSTDIR\text.077"
  Delete "$INSTDIR\text.078"
  Delete "$INSTDIR\text.079"
  Delete "$INSTDIR\text.080"
  Delete "$INSTDIR\text.083"
  Delete "$INSTDIR\text.085"
  Delete "$INSTDIR\text.087"
  Delete "$INSTDIR\text.090"
  Delete "$INSTDIR\text.200"
  Delete "$INSTDIR\text.255"
  Delete "$INSTDIR\text.600"
  Delete "$INSTDIR\text.601"
  Delete "$INSTDIR\text.603"
  Delete "$INSTDIR\text.604"
  Delete "$INSTDIR\text.605"
  Delete "$INSTDIR\text.606"
  Delete "$INSTDIR\text.607"
  Delete "$INSTDIR\text.608"
  Delete "$INSTDIR\text.609"
  Delete "$INSTDIR\text.610"
  Delete "$INSTDIR\text.611"
  Delete "$INSTDIR\text.612"
  Delete "$INSTDIR\text.613"
  Delete "$INSTDIR\text.616"
  Delete "$INSTDIR\text.780"
  Delete "$INSTDIR\text.782"
  Delete "$INSTDIR\text.784"
  Delete "$INSTDIR\text.800"
  Delete "$INSTDIR\text.803"
  Delete "$INSTDIR\text.804"
  Delete "$INSTDIR\text.899"
  Delete "$INSTDIR\text.950"
  Delete "$INSTDIR\text.990"
  Delete "$INSTDIR\text.993"
  Delete "$INSTDIR\text.994"
  Delete "$INSTDIR\text.996"
  Delete "$INSTDIR\text.997"
  Delete "$INSTDIR\text.999"
  
  ; Remove uninstaller
  Delete "$INSTDIR\Uninstall_Hebrew_Patch.exe"

  ; Remove registry keys
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\KQ1_Hebrew_Patch"
  DeleteRegKey HKLM "Software\KQ1_Hebrew_Patch"

SectionEnd
