; Quest For Glory I Hebrew Patch Installer
; NSIS Script

;--------------------------------
; General Attributes

Name "1-הרצון לעוצמה (EGA) - תרגום עברי"
OutFile "QFG1_Hebrew_Patch_Setup.exe"
InstallDir ""
RequestExecutionLevel admin

;--------------------------------
; Version Information

VIProductVersion "1.0.0.0"
VIAddVersionKey "ProductName" "Quest For Glory I Hebrew Patch"
VIAddVersionKey "FileDescription" "Hebrew Translation Patch for Quest For Glory I (EGA)"
VIAddVersionKey "FileVersion" "1.0.0.0"
VIAddVersionKey "ProductVersion" "1.0.0.0"
VIAddVersionKey "LegalCopyright" "Hebrew Translation Team"

;--------------------------------
; Modern UI

!include "MUI2.nsh"

;--------------------------------
; MUI Settings

!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Custom Hebrew text
!define MUI_WELCOMEPAGE_TITLE "ברוכים הבאים להתקנת התרגום העברי"
!define MUI_WELCOMEPAGE_TEXT "אשף זה ידריך אותך בהתקנת התרגום העברי למשחק הרצון לעוצמה-1 (גרסת EGA).$\r$\n$\r$\nלחץ 'הבא' כדי להמשיך."
!define MUI_DIRECTORYPAGE_TEXT_TOP "בחר את תיקיית המשחק שבה מותקן הרצון לעוצמה-1 (גרסת EGA)."
!define MUI_FINISHPAGE_TITLE "ההתקנה הושלמה בהצלחה"
!define MUI_FINISHPAGE_TEXT "התרגום העברי הותקן בהצלחה.$\r$\n$\r$\nלחץ 'סיום' כדי לסגור אשף זה."

;--------------------------------
; Pages

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

;--------------------------------
; Languages

!insertmacro MUI_LANGUAGE "Hebrew"

;--------------------------------
; Validation Function

Function .onVerifyInstDir
  ; Check if resource.map exists
  IfFileExists "$INSTDIR\resource.map" 0 invalid_dir
  
  ; Get file size of resource.map
  ClearErrors
  FileOpen $0 "$INSTDIR\resource.map" r
  FileSeek $0 0 END $1
  FileClose $0
  
  ; Check if file size matches a known QFG1 EGA resource.map (6,474 or 6,432 bytes)
  IntCmp $1 6474 valid_dir check_6432 check_6432
  check_6432:
    IntCmp $1 6432 valid_dir invalid_dir invalid_dir
  
  valid_dir:
    ; Directory is valid
    Return
  
  invalid_dir:
    ; Directory is invalid - abort
    Abort
FunctionEnd

;--------------------------------
; Installer Sections

Section "הרצון לעוצמה-1 - תרגום עברי" SecMain

  SetOutPath "$INSTDIR"
  
  ; Set overwrite on to replace existing files
  SetOverwrite try
  
  ; Copy assets (fonts, views, vocab, extras)
  File "games_assets\qfg1\bin_new\QFG1_Instructions_eng.txt"
  File "games_assets\qfg1\bin_new\Quest_for_Glory_1_-_Manual_text.pdf"
  File "games_assets\qfg1\bin_new\font.000"
  File "games_assets\qfg1\bin_new\font.300"
  File "games_assets\qfg1\bin_new\font.999"
  File "games_assets\qfg1\bin_new\pic.318"
  File "games_assets\qfg1\bin_new\view.095"
  File "games_assets\qfg1\bin_new\view.165"
  File "games_assets\qfg1\bin_new\view.300"
  File "games_assets\qfg1\bin_new\view.310"
  File "games_assets\qfg1\bin_new\view.311"
  File "games_assets\qfg1\bin_new\view.318"
  File "games_assets\qfg1\bin_new\view.320"
  File "games_assets\qfg1\bin_new\view.506"
  File "games_assets\qfg1\bin_new\vocab.000"

  ; Copy all script files
  File "games_assets\qfg1\bin_new\script.000"
  File "games_assets\qfg1\bin_new\script.005"
  File "games_assets\qfg1\bin_new\script.014"
  File "games_assets\qfg1\bin_new\script.022"
  File "games_assets\qfg1\bin_new\script.029"
  File "games_assets\qfg1\bin_new\script.031"
  File "games_assets\qfg1\bin_new\script.053"
  File "games_assets\qfg1\bin_new\script.054"
  File "games_assets\qfg1\bin_new\script.055"
  File "games_assets\qfg1\bin_new\script.060"
  File "games_assets\qfg1\bin_new\script.064"
  File "games_assets\qfg1\bin_new\script.065"
  File "games_assets\qfg1\bin_new\script.070"
  File "games_assets\qfg1\bin_new\script.073"
  File "games_assets\qfg1\bin_new\script.081"
  File "games_assets\qfg1\bin_new\script.083"
  File "games_assets\qfg1\bin_new\script.084"
  File "games_assets\qfg1\bin_new\script.097"
  File "games_assets\qfg1\bin_new\script.131"
  File "games_assets\qfg1\bin_new\script.141"
  File "games_assets\qfg1\bin_new\script.166"
  File "games_assets\qfg1\bin_new\script.172"
  File "games_assets\qfg1\bin_new\script.203"
  File "games_assets\qfg1\bin_new\script.204"
  File "games_assets\qfg1\bin_new\script.213"
  File "games_assets\qfg1\bin_new\script.214"
  File "games_assets\qfg1\bin_new\script.255"
  File "games_assets\qfg1\bin_new\script.300"
  File "games_assets\qfg1\bin_new\script.301"
  File "games_assets\qfg1\bin_new\script.302"
  File "games_assets\qfg1\bin_new\script.311"
  File "games_assets\qfg1\bin_new\script.313"
  File "games_assets\qfg1\bin_new\script.314"
  File "games_assets\qfg1\bin_new\script.321"
  File "games_assets\qfg1\bin_new\script.331"
  File "games_assets\qfg1\bin_new\script.332"
  File "games_assets\qfg1\bin_new\script.333"
  File "games_assets\qfg1\bin_new\script.334"
  File "games_assets\qfg1\bin_new\script.802"
  File "games_assets\qfg1\bin_new\script.997"

  ; Copy all text files
  File "games_assets\qfg1\bin_new\text.000"
  File "games_assets\qfg1\bin_new\text.002"
  File "games_assets\qfg1\bin_new\text.003"
  File "games_assets\qfg1\bin_new\text.004"
  File "games_assets\qfg1\bin_new\text.005"
  File "games_assets\qfg1\bin_new\text.006"
  File "games_assets\qfg1\bin_new\text.007"
  File "games_assets\qfg1\bin_new\text.008"
  File "games_assets\qfg1\bin_new\text.009"
  File "games_assets\qfg1\bin_new\text.010"
  File "games_assets\qfg1\bin_new\text.013"
  File "games_assets\qfg1\bin_new\text.014"
  File "games_assets\qfg1\bin_new\text.015"
  File "games_assets\qfg1\bin_new\text.016"
  File "games_assets\qfg1\bin_new\text.021"
  File "games_assets\qfg1\bin_new\text.022"
  File "games_assets\qfg1\bin_new\text.027"
  File "games_assets\qfg1\bin_new\text.028"
  File "games_assets\qfg1\bin_new\text.029"
  File "games_assets\qfg1\bin_new\text.030"
  File "games_assets\qfg1\bin_new\text.031"
  File "games_assets\qfg1\bin_new\text.032"
  File "games_assets\qfg1\bin_new\text.033"
  File "games_assets\qfg1\bin_new\text.034"
  File "games_assets\qfg1\bin_new\text.035"
  File "games_assets\qfg1\bin_new\text.036"
  File "games_assets\qfg1\bin_new\text.037"
  File "games_assets\qfg1\bin_new\text.038"
  File "games_assets\qfg1\bin_new\text.039"
  File "games_assets\qfg1\bin_new\text.040"
  File "games_assets\qfg1\bin_new\text.041"
  File "games_assets\qfg1\bin_new\text.045"
  File "games_assets\qfg1\bin_new\text.053"
  File "games_assets\qfg1\bin_new\text.054"
  File "games_assets\qfg1\bin_new\text.055"
  File "games_assets\qfg1\bin_new\text.057"
  File "games_assets\qfg1\bin_new\text.058"
  File "games_assets\qfg1\bin_new\text.060"
  File "games_assets\qfg1\bin_new\text.064"
  File "games_assets\qfg1\bin_new\text.065"
  File "games_assets\qfg1\bin_new\text.067"
  File "games_assets\qfg1\bin_new\text.068"
  File "games_assets\qfg1\bin_new\text.070"
  File "games_assets\qfg1\bin_new\text.073"
  File "games_assets\qfg1\bin_new\text.074"
  File "games_assets\qfg1\bin_new\text.076"
  File "games_assets\qfg1\bin_new\text.077"
  File "games_assets\qfg1\bin_new\text.078"
  File "games_assets\qfg1\bin_new\text.080"
  File "games_assets\qfg1\bin_new\text.081"
  File "games_assets\qfg1\bin_new\text.082"
  File "games_assets\qfg1\bin_new\text.083"
  File "games_assets\qfg1\bin_new\text.084"
  File "games_assets\qfg1\bin_new\text.085"
  File "games_assets\qfg1\bin_new\text.087"
  File "games_assets\qfg1\bin_new\text.088"
  File "games_assets\qfg1\bin_new\text.089"
  File "games_assets\qfg1\bin_new\text.091"
  File "games_assets\qfg1\bin_new\text.093"
  File "games_assets\qfg1\bin_new\text.094"
  File "games_assets\qfg1\bin_new\text.095"
  File "games_assets\qfg1\bin_new\text.096"
  File "games_assets\qfg1\bin_new\text.097"
  File "games_assets\qfg1\bin_new\text.101"
  File "games_assets\qfg1\bin_new\text.102"
  File "games_assets\qfg1\bin_new\text.103"
  File "games_assets\qfg1\bin_new\text.104"
  File "games_assets\qfg1\bin_new\text.113"
  File "games_assets\qfg1\bin_new\text.114"
  File "games_assets\qfg1\bin_new\text.115"
  File "games_assets\qfg1\bin_new\text.116"
  File "games_assets\qfg1\bin_new\text.131"
  File "games_assets\qfg1\bin_new\text.132"
  File "games_assets\qfg1\bin_new\text.133"
  File "games_assets\qfg1\bin_new\text.134"
  File "games_assets\qfg1\bin_new\text.135"
  File "games_assets\qfg1\bin_new\text.137"
  File "games_assets\qfg1\bin_new\text.138"
  File "games_assets\qfg1\bin_new\text.139"
  File "games_assets\qfg1\bin_new\text.140"
  File "games_assets\qfg1\bin_new\text.141"
  File "games_assets\qfg1\bin_new\text.143"
  File "games_assets\qfg1\bin_new\text.144"
  File "games_assets\qfg1\bin_new\text.145"
  File "games_assets\qfg1\bin_new\text.150"
  File "games_assets\qfg1\bin_new\text.155"
  File "games_assets\qfg1\bin_new\text.156"
  File "games_assets\qfg1\bin_new\text.157"
  File "games_assets\qfg1\bin_new\text.158"
  File "games_assets\qfg1\bin_new\text.159"
  File "games_assets\qfg1\bin_new\text.160"
  File "games_assets\qfg1\bin_new\text.165"
  File "games_assets\qfg1\bin_new\text.166"
  File "games_assets\qfg1\bin_new\text.167"
  File "games_assets\qfg1\bin_new\text.168"
  File "games_assets\qfg1\bin_new\text.170"
  File "games_assets\qfg1\bin_new\text.171"
  File "games_assets\qfg1\bin_new\text.172"
  File "games_assets\qfg1\bin_new\text.186"
  File "games_assets\qfg1\bin_new\text.187"
  File "games_assets\qfg1\bin_new\text.188"
  File "games_assets\qfg1\bin_new\text.190"
  File "games_assets\qfg1\bin_new\text.191"
  File "games_assets\qfg1\bin_new\text.193"
  File "games_assets\qfg1\bin_new\text.203"
  File "games_assets\qfg1\bin_new\text.204"
  File "games_assets\qfg1\bin_new\text.206"
  File "games_assets\qfg1\bin_new\text.210"
  File "games_assets\qfg1\bin_new\text.213"
  File "games_assets\qfg1\bin_new\text.214"
  File "games_assets\qfg1\bin_new\text.215"
  File "games_assets\qfg1\bin_new\text.216"
  File "games_assets\qfg1\bin_new\text.221"
  File "games_assets\qfg1\bin_new\text.222"
  File "games_assets\qfg1\bin_new\text.223"
  File "games_assets\qfg1\bin_new\text.224"
  File "games_assets\qfg1\bin_new\text.225"
  File "games_assets\qfg1\bin_new\text.226"
  File "games_assets\qfg1\bin_new\text.227"
  File "games_assets\qfg1\bin_new\text.228"
  File "games_assets\qfg1\bin_new\text.230"
  File "games_assets\qfg1\bin_new\text.231"
  File "games_assets\qfg1\bin_new\text.232"
  File "games_assets\qfg1\bin_new\text.233"
  File "games_assets\qfg1\bin_new\text.234"
  File "games_assets\qfg1\bin_new\text.235"
  File "games_assets\qfg1\bin_new\text.236"
  File "games_assets\qfg1\bin_new\text.237"
  File "games_assets\qfg1\bin_new\text.239"
  File "games_assets\qfg1\bin_new\text.255"
  File "games_assets\qfg1\bin_new\text.257"
  File "games_assets\qfg1\bin_new\text.271"
  File "games_assets\qfg1\bin_new\text.272"
  File "games_assets\qfg1\bin_new\text.273"
  File "games_assets\qfg1\bin_new\text.274"
  File "games_assets\qfg1\bin_new\text.276"
  File "games_assets\qfg1\bin_new\text.277"
  File "games_assets\qfg1\bin_new\text.278"
  File "games_assets\qfg1\bin_new\text.279"
  File "games_assets\qfg1\bin_new\text.288"
  File "games_assets\qfg1\bin_new\text.289"
  File "games_assets\qfg1\bin_new\text.290"
  File "games_assets\qfg1\bin_new\text.291"
  File "games_assets\qfg1\bin_new\text.292"
  File "games_assets\qfg1\bin_new\text.293"
  File "games_assets\qfg1\bin_new\text.294"
  File "games_assets\qfg1\bin_new\text.295"
  File "games_assets\qfg1\bin_new\text.296"
  File "games_assets\qfg1\bin_new\text.297"
  File "games_assets\qfg1\bin_new\text.298"
  File "games_assets\qfg1\bin_new\text.300"
  File "games_assets\qfg1\bin_new\text.301"
  File "games_assets\qfg1\bin_new\text.310"
  File "games_assets\qfg1\bin_new\text.311"
  File "games_assets\qfg1\bin_new\text.313"
  File "games_assets\qfg1\bin_new\text.314"
  File "games_assets\qfg1\bin_new\text.318"
  File "games_assets\qfg1\bin_new\text.320"
  File "games_assets\qfg1\bin_new\text.321"
  File "games_assets\qfg1\bin_new\text.322"
  File "games_assets\qfg1\bin_new\text.330"
  File "games_assets\qfg1\bin_new\text.331"
  File "games_assets\qfg1\bin_new\text.332"
  File "games_assets\qfg1\bin_new\text.333"
  File "games_assets\qfg1\bin_new\text.334"
  File "games_assets\qfg1\bin_new\text.335"
  File "games_assets\qfg1\bin_new\text.336"
  File "games_assets\qfg1\bin_new\text.339"
  File "games_assets\qfg1\bin_new\text.340"
  File "games_assets\qfg1\bin_new\text.341"
  File "games_assets\qfg1\bin_new\text.445"
  File "games_assets\qfg1\bin_new\text.465"
  File "games_assets\qfg1\bin_new\text.600"
  File "games_assets\qfg1\bin_new\text.601"
  File "games_assets\qfg1\bin_new\text.801"
  File "games_assets\qfg1\bin_new\text.804"
  File "games_assets\qfg1\bin_new\text.806"
  File "games_assets\qfg1\bin_new\text.807"
  File "games_assets\qfg1\bin_new\text.811"
  File "games_assets\qfg1\bin_new\text.983"
  File "games_assets\qfg1\bin_new\text.990"
  File "games_assets\qfg1\bin_new\text.993"
  File "games_assets\qfg1\bin_new\text.994"
  File "games_assets\qfg1\bin_new\text.996"
  File "games_assets\qfg1\bin_new\text.997"
  File "games_assets\qfg1\bin_new\text.999"
  ; Store installation folder
  WriteRegStr HKLM "Software\QFG1_Hebrew_Patch" "Install_Dir" "$INSTDIR"
  
  ; Create uninstaller
  WriteUninstaller "$INSTDIR\Uninstall_Hebrew_Patch.exe"
  
  ; Write uninstall registry keys
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\QFG1_Hebrew_Patch" "DisplayName" "הרצון לעוצמה-1 (EGA) - Hebrew Patch"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\QFG1_Hebrew_Patch" "UninstallString" '"$INSTDIR\Uninstall_Hebrew_Patch.exe"'
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\QFG1_Hebrew_Patch" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\QFG1_Hebrew_Patch" "NoRepair" 1

SectionEnd

;--------------------------------
; Uninstaller Section

Section "Uninstall"

  ; Remove asset files
  Delete "$INSTDIR\QFG1_Instructions_eng.txt"
  Delete "$INSTDIR\Quest_for_Glory_1_-_Manual_text.pdf"
  Delete "$INSTDIR\font.000"
  Delete "$INSTDIR\font.300"
  Delete "$INSTDIR\font.999"
  Delete "$INSTDIR\pic.318"
  Delete "$INSTDIR\view.095"
  Delete "$INSTDIR\view.165"
  Delete "$INSTDIR\view.300"
  Delete "$INSTDIR\view.310"
  Delete "$INSTDIR\view.311"
  Delete "$INSTDIR\view.318"
  Delete "$INSTDIR\view.320"
  Delete "$INSTDIR\view.506"
  Delete "$INSTDIR\vocab.000"

  ; Remove script files
  Delete "$INSTDIR\script.000"
  Delete "$INSTDIR\script.005"
  Delete "$INSTDIR\script.014"
  Delete "$INSTDIR\script.022"
  Delete "$INSTDIR\script.029"
  Delete "$INSTDIR\script.031"
  Delete "$INSTDIR\script.053"
  Delete "$INSTDIR\script.054"
  Delete "$INSTDIR\script.055"
  Delete "$INSTDIR\script.060"
  Delete "$INSTDIR\script.064"
  Delete "$INSTDIR\script.065"
  Delete "$INSTDIR\script.070"
  Delete "$INSTDIR\script.073"
  Delete "$INSTDIR\script.081"
  Delete "$INSTDIR\script.083"
  Delete "$INSTDIR\script.084"
  Delete "$INSTDIR\script.097"
  Delete "$INSTDIR\script.131"
  Delete "$INSTDIR\script.141"
  Delete "$INSTDIR\script.166"
  Delete "$INSTDIR\script.172"
  Delete "$INSTDIR\script.203"
  Delete "$INSTDIR\script.204"
  Delete "$INSTDIR\script.213"
  Delete "$INSTDIR\script.214"
  Delete "$INSTDIR\script.255"
  Delete "$INSTDIR\script.300"
  Delete "$INSTDIR\script.301"
  Delete "$INSTDIR\script.302"
  Delete "$INSTDIR\script.311"
  Delete "$INSTDIR\script.313"
  Delete "$INSTDIR\script.314"
  Delete "$INSTDIR\script.321"
  Delete "$INSTDIR\script.331"
  Delete "$INSTDIR\script.332"
  Delete "$INSTDIR\script.333"
  Delete "$INSTDIR\script.334"
  Delete "$INSTDIR\script.802"
  Delete "$INSTDIR\script.997"

  ; Remove text files
  Delete "$INSTDIR\text.000"
  Delete "$INSTDIR\text.002"
  Delete "$INSTDIR\text.003"
  Delete "$INSTDIR\text.004"
  Delete "$INSTDIR\text.005"
  Delete "$INSTDIR\text.006"
  Delete "$INSTDIR\text.007"
  Delete "$INSTDIR\text.008"
  Delete "$INSTDIR\text.009"
  Delete "$INSTDIR\text.010"
  Delete "$INSTDIR\text.013"
  Delete "$INSTDIR\text.014"
  Delete "$INSTDIR\text.015"
  Delete "$INSTDIR\text.016"
  Delete "$INSTDIR\text.021"
  Delete "$INSTDIR\text.022"
  Delete "$INSTDIR\text.027"
  Delete "$INSTDIR\text.028"
  Delete "$INSTDIR\text.029"
  Delete "$INSTDIR\text.030"
  Delete "$INSTDIR\text.031"
  Delete "$INSTDIR\text.032"
  Delete "$INSTDIR\text.033"
  Delete "$INSTDIR\text.034"
  Delete "$INSTDIR\text.035"
  Delete "$INSTDIR\text.036"
  Delete "$INSTDIR\text.037"
  Delete "$INSTDIR\text.038"
  Delete "$INSTDIR\text.039"
  Delete "$INSTDIR\text.040"
  Delete "$INSTDIR\text.041"
  Delete "$INSTDIR\text.045"
  Delete "$INSTDIR\text.053"
  Delete "$INSTDIR\text.054"
  Delete "$INSTDIR\text.055"
  Delete "$INSTDIR\text.057"
  Delete "$INSTDIR\text.058"
  Delete "$INSTDIR\text.060"
  Delete "$INSTDIR\text.064"
  Delete "$INSTDIR\text.065"
  Delete "$INSTDIR\text.067"
  Delete "$INSTDIR\text.068"
  Delete "$INSTDIR\text.070"
  Delete "$INSTDIR\text.073"
  Delete "$INSTDIR\text.074"
  Delete "$INSTDIR\text.076"
  Delete "$INSTDIR\text.077"
  Delete "$INSTDIR\text.078"
  Delete "$INSTDIR\text.080"
  Delete "$INSTDIR\text.081"
  Delete "$INSTDIR\text.082"
  Delete "$INSTDIR\text.083"
  Delete "$INSTDIR\text.084"
  Delete "$INSTDIR\text.085"
  Delete "$INSTDIR\text.087"
  Delete "$INSTDIR\text.088"
  Delete "$INSTDIR\text.089"
  Delete "$INSTDIR\text.091"
  Delete "$INSTDIR\text.093"
  Delete "$INSTDIR\text.094"
  Delete "$INSTDIR\text.095"
  Delete "$INSTDIR\text.096"
  Delete "$INSTDIR\text.097"
  Delete "$INSTDIR\text.101"
  Delete "$INSTDIR\text.102"
  Delete "$INSTDIR\text.103"
  Delete "$INSTDIR\text.104"
  Delete "$INSTDIR\text.113"
  Delete "$INSTDIR\text.114"
  Delete "$INSTDIR\text.115"
  Delete "$INSTDIR\text.116"
  Delete "$INSTDIR\text.131"
  Delete "$INSTDIR\text.132"
  Delete "$INSTDIR\text.133"
  Delete "$INSTDIR\text.134"
  Delete "$INSTDIR\text.135"
  Delete "$INSTDIR\text.137"
  Delete "$INSTDIR\text.138"
  Delete "$INSTDIR\text.139"
  Delete "$INSTDIR\text.140"
  Delete "$INSTDIR\text.141"
  Delete "$INSTDIR\text.143"
  Delete "$INSTDIR\text.144"
  Delete "$INSTDIR\text.145"
  Delete "$INSTDIR\text.150"
  Delete "$INSTDIR\text.155"
  Delete "$INSTDIR\text.156"
  Delete "$INSTDIR\text.157"
  Delete "$INSTDIR\text.158"
  Delete "$INSTDIR\text.159"
  Delete "$INSTDIR\text.160"
  Delete "$INSTDIR\text.165"
  Delete "$INSTDIR\text.166"
  Delete "$INSTDIR\text.167"
  Delete "$INSTDIR\text.168"
  Delete "$INSTDIR\text.170"
  Delete "$INSTDIR\text.171"
  Delete "$INSTDIR\text.172"
  Delete "$INSTDIR\text.186"
  Delete "$INSTDIR\text.187"
  Delete "$INSTDIR\text.188"
  Delete "$INSTDIR\text.190"
  Delete "$INSTDIR\text.191"
  Delete "$INSTDIR\text.193"
  Delete "$INSTDIR\text.203"
  Delete "$INSTDIR\text.204"
  Delete "$INSTDIR\text.206"
  Delete "$INSTDIR\text.210"
  Delete "$INSTDIR\text.213"
  Delete "$INSTDIR\text.214"
  Delete "$INSTDIR\text.215"
  Delete "$INSTDIR\text.216"
  Delete "$INSTDIR\text.221"
  Delete "$INSTDIR\text.222"
  Delete "$INSTDIR\text.223"
  Delete "$INSTDIR\text.224"
  Delete "$INSTDIR\text.225"
  Delete "$INSTDIR\text.226"
  Delete "$INSTDIR\text.227"
  Delete "$INSTDIR\text.228"
  Delete "$INSTDIR\text.230"
  Delete "$INSTDIR\text.231"
  Delete "$INSTDIR\text.232"
  Delete "$INSTDIR\text.233"
  Delete "$INSTDIR\text.234"
  Delete "$INSTDIR\text.235"
  Delete "$INSTDIR\text.236"
  Delete "$INSTDIR\text.237"
  Delete "$INSTDIR\text.239"
  Delete "$INSTDIR\text.255"
  Delete "$INSTDIR\text.257"
  Delete "$INSTDIR\text.271"
  Delete "$INSTDIR\text.272"
  Delete "$INSTDIR\text.273"
  Delete "$INSTDIR\text.274"
  Delete "$INSTDIR\text.276"
  Delete "$INSTDIR\text.277"
  Delete "$INSTDIR\text.278"
  Delete "$INSTDIR\text.279"
  Delete "$INSTDIR\text.288"
  Delete "$INSTDIR\text.289"
  Delete "$INSTDIR\text.290"
  Delete "$INSTDIR\text.291"
  Delete "$INSTDIR\text.292"
  Delete "$INSTDIR\text.293"
  Delete "$INSTDIR\text.294"
  Delete "$INSTDIR\text.295"
  Delete "$INSTDIR\text.296"
  Delete "$INSTDIR\text.297"
  Delete "$INSTDIR\text.298"
  Delete "$INSTDIR\text.300"
  Delete "$INSTDIR\text.301"
  Delete "$INSTDIR\text.310"
  Delete "$INSTDIR\text.311"
  Delete "$INSTDIR\text.313"
  Delete "$INSTDIR\text.314"
  Delete "$INSTDIR\text.318"
  Delete "$INSTDIR\text.320"
  Delete "$INSTDIR\text.321"
  Delete "$INSTDIR\text.322"
  Delete "$INSTDIR\text.330"
  Delete "$INSTDIR\text.331"
  Delete "$INSTDIR\text.332"
  Delete "$INSTDIR\text.333"
  Delete "$INSTDIR\text.334"
  Delete "$INSTDIR\text.335"
  Delete "$INSTDIR\text.336"
  Delete "$INSTDIR\text.339"
  Delete "$INSTDIR\text.340"
  Delete "$INSTDIR\text.341"
  Delete "$INSTDIR\text.445"
  Delete "$INSTDIR\text.465"
  Delete "$INSTDIR\text.600"
  Delete "$INSTDIR\text.601"
  Delete "$INSTDIR\text.801"
  Delete "$INSTDIR\text.804"
  Delete "$INSTDIR\text.806"
  Delete "$INSTDIR\text.807"
  Delete "$INSTDIR\text.811"
  Delete "$INSTDIR\text.983"
  Delete "$INSTDIR\text.990"
  Delete "$INSTDIR\text.993"
  Delete "$INSTDIR\text.994"
  Delete "$INSTDIR\text.996"
  Delete "$INSTDIR\text.997"
  Delete "$INSTDIR\text.999"
  
  ; Remove uninstaller
  Delete "$INSTDIR\Uninstall_Hebrew_Patch.exe"

  ; Remove registry keys
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\QFG1_Hebrew_Patch"
  DeleteRegKey HKLM "Software\QFG1_Hebrew_Patch"

SectionEnd
